//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial1.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Computador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computador()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int Codigo { get; set; }
        public string Referencia { get; set; }
        public int númeroProcesadores { get; set; }
        public string marcaProcesador { get; set; }
        public int tamanoDiscoDuro { get; set; }
        public int tamanoMemoria { get; set; }
        public string componente { get; set; }
        public int IdTipoComputador { get; set; }
        public Nullable<bool> Activo { get; set; }
        [JsonIgnore]
        public virtual TipoComputador TipoComputador { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
